create table athlete(
    id int primary key generated by default as identity,
    login varchar(100) unique not null,
    password varchar not null,
    name varchar(100) not null,
    role varchar(30) not null,
    birth_date date not null,
	body_weight DOUBLE PRECISION,
	body_height DOUBLE PRECISION,
	id_training_program int,
	FOREIGN KEY(id_training_program) REFERENCES training_program(id)
);

create table exercise (
  id int primary key generated by default as identity,
  name varchar(100) unique not null,
  description varchar(200)

);

create table training_program(
    id int primary key generated by default as identity ,
    program_name varchar(100)
);

create TABLE set_exercises(
	id int primary key generated by default as identity,
	name VARCHAR(100),
	approache int,
	repeats int,
	weight double precision,
	day_of_week int,
	id_exercise int not null,
	FOREIGN KEY(id_exercise) REFERENCES exercise(id),
	id_training_program int,
	FOREIGN KEY(id_training_program) REFERENCES training_program(id)
);

create TABLE appointed_training_program(
	id int primary key generated by default as identity,
	id_athlete int not null,
	FOREIGN KEY(id_athlete) REFERENCES athlete(id),
	id_training_program int not null,
	FOREIGN KEY(id_training_program) REFERENCES training_program(id),
	start_date TIMESTAMP,
	end_date TIMESTAMP
);

CREATE TABLE done_exercises(
	id int primary key generated by default as identity,
	id_athlete int NOT NULL,
	FOREIGN KEY(id_athlete) REFERENCES athlete(id),
	id_exercise int NOT NULL,
	FOREIGN KEY(id_exercise) REFERENCES exercise(id),
	done_date TIMESTAMP,
	repeats int,
	weight double precision
);

CREATE TABLE records(
	id int primary key generated by default as identity,
	id_athlete int NOT NULL,
	FOREIGN KEY(id_athlete) REFERENCES athlete(id),
	id_exercise int NOT NULL,
	FOREIGN KEY(id_exercise) REFERENCES exercise(id),
	done_date TIMESTAMP,
	repeats int,
	weight DOUBLE PRECISION,
	CONSTRAINT composite_key UNIQUE (id_athlete, id_exercise, repeats, weight)
);
